### Development environment configuration
[development.network]
rpc-url = "http://localhost:8000/rpc"
network-passphrase = "Standalone Network ; February 2017"
run-locally = true

[[development.accounts]]
name = "employer"
default = true

[[development.accounts]]
name = "worker"

[development.contracts.pay_shift]
client = true

### Staging = Stellar Testnet (hackathon demo)
[staging.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[staging.accounts]]
name = "employer"
default = true

[[staging.accounts]]
name = "worker"

[staging.contracts]
pay_shift = { id = "CBPCPL6JJTVLYFT2DLTLA3FAFQHPD3LZYARCMF3CFCZF4D2JS32FNDVO" }

### Production — unused in this hackathon (Testnet only)
[production.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[production.accounts]]
name = "employer"
default = true

[production.contracts]
pay_shift = { id = "CBPCPL6JJTVLYFT2DLTLA3FAFQHPD3LZYARCMF3CFCZF4D2JS32FNDVO" }
